@startuml
'https://plantuml.com/sequence-diagram

skinparam classFontColor 007BFF
skinparam classFontSize 12
skinparam classFontName Aapex
skinparam backgroundColor white
skinparam minClassWidth 155
skinparam nodesep 34
skinparam ranksep 70

skinparam sequence {
ArrowColor 007BFF
ActorBorderColor 007BFF
LifeLineBorderColor 007BFF
LifeLineBackgroundColor 007BFF

ParticipantBorderColor 007BFF
ParticipantBackgroundColor 007BFF
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

'ActorBackgroundColor aqua
ActorFontColor 007BFF
ActorFontSize 17
ActorFontName Aapex
}

skinparam class {
BorderColor 007BFF
ArrowColor 007BFF
BackgroundColor white
}

skinparam interface {
BorderColor 007BFF
ArrowColor 007BFF
}

skinparam note {
BorderColor 007BFF
BackgroundColor 7ACFF5
}


autonumber

header EBSI DID Registration
title
EBSI DID Registration
end title
autonumber
actor "Legal Entity" as LE
participant "Enterprise Wallet\n(from LE)" as EW
participant "eSSIF Onboarding Service\n(Trusted Issuer)" as TI
participant "EBSI DID Registry" as RE

LE -> EW: Create DID
activate EW
EW --> EW: Generate DID (ETH key, DID key, DID Doc)
EW -> TI: Request Verifiable Authorization
TI --> EW: Request DID prove
EW -> TI: Signed challenge
TI -> TI: Validate DID doc
TI -> TI: Generate Verifiable Authorization
TI --> EW: Return Verifiable Authorization
EW --> RE: Insert DID
RE --> RE: Validate request + generate unsigned ETH transaction
RE --> EW: Return unsigned transaction
EW --> RE: Sign and return ETH transaction
RE --> RE: Execute transaction
RE --> EW: DID inserted successfully 
destroy EW

EW --> LE: Successful process
@enduml
