@startuml
'https://plantuml.com/sequence-diagram

skinparam classFontColor 007BFF
skinparam classFontSize 12
skinparam classFontName Aapex
skinparam backgroundColor white
skinparam minClassWidth 155
skinparam nodesep 34
skinparam ranksep 70

skinparam sequence {
ArrowColor 007BFF
ActorBorderColor 007BFF
LifeLineBorderColor 007BFF
LifeLineBackgroundColor 007BFF

ParticipantBorderColor 007BFF
ParticipantBackgroundColor 007BFF
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

'ActorBackgroundColor aqua
ActorFontColor 007BFF
ActorFontSize 17
ActorFontName Aapex
}

skinparam class {
BorderColor 007BFF
ArrowColor 007BFF
BackgroundColor white
}

skinparam interface {
BorderColor 007BFF
ArrowColor 007BFF
}

skinparam note {
BorderColor 007BFF
BackgroundColor 7ACFF5
}


autonumber

header Legal Entity - A high-level flow
title
Legal Entity Onboards
end title
autonumber
actor "Legal Entity" as LE
participant "Enterprise Wallet\n(from LE)" as EW
participant "eSSIF Onboarding Service\n(Trusted Issuer)" as TI

LE -> TI: Request V.ID (Manually)
TI --> LE: Request Credential (QR, URI, ...)
LE -> EW: Trigger Wallet
EW -> TI: Request V.ID
TI -> TI: Generate DID Auth Request
TI --> EW: Request DID prove
EW --> LE: Notify\nDID ownership request
note over TI, EW: The process is blocked till the Legal Entity receives its DID
LE -> EW: Create a new DID

hnote across:SUB-FLOW: DID Registration

EW -> TI: Response DID ownership
TI -> TI: Validate DID ownership
TI --> EW: 200 <V.ID Request OK>
TI -> TI: Generate <V.ID>
EW -> TI: [GET] /credentials
TI --> EW: 200 <V.ID>

EW --> LE: Successful process
@enduml
