@startuml
'https://plantuml.com/sequence-diagram

skinparam classFontColor 007BFF
skinparam classFontSize 12
skinparam classFontName Aapex
skinparam backgroundColor white
skinparam minClassWidth 155
skinparam nodesep 34
skinparam ranksep 70

skinparam sequence {
ArrowColor 007BFF
ActorBorderColor 007BFF
LifeLineBorderColor 007BFF
LifeLineBackgroundColor 007BFF

ParticipantBorderColor 007BFF
ParticipantBackgroundColor 007BFF
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

'ActorBackgroundColor aqua
ActorFontColor 007BFF
ActorFontSize 17
ActorFontName Aapex
}

skinparam class {
BorderColor 007BFF
ArrowColor 007BFF
BackgroundColor white
}

skinparam interface {
BorderColor 007BFF
ArrowColor 007BFF
}

skinparam note {
BorderColor 007BFF
BackgroundColor 7ACFF5
}


autonumber

header VC issuance flow
title
Credential issuance from a Legal Entity to a Natural Person.
end title
autonumber
actor "Natural Person" as NP
participant "User Wallet\n(from NP)" as UW
participant "Trusted Issuer Service" as TI
participant "Enterprise Wallet \n(from TI)" as EW

NP -> TI: getCredentials()
TI -> EW: Generate <DID Auth Request>
EW --> TI: <DID Auth Request>
TI --> NP: <DID Auth Request> (QR, URI, ...)
NP -> UW: Validate <DID Auth Request>
note over NP, UW: Choose DID used in the DID Authentication
NP -> UW: Consent + Generate <DID Auth Response>
UW -> EW: callback <DID Auth Response>
EW -> EW: Validate <DID Auth Response>
EW --> UW: Authenticated session established
NP -> TI: getCredentials()
TI --> UW: 200 <V.ID>
UW --> NP: Successful process
@enduml
