FROM openjdk:15-alpine
COPY build/libs/letstrust-ssi-core-with-dependencies-1.0-SNAPSHOT.jar letstrust-ssi-core-with-dependencies-1.0-SNAPSHOT.jar
CMD java -jar letstrust-ssi-core-with-dependencies-1.0-SNAPSHOT.jar
